version: '3.5'

services:
  tumo-cloud-ui:
    image: tumo-cloud-ui
    build:
      context: .
    restart: always
    container_name: tumo-cloud-ui
    ports:
      - 9000:80
    networks:
      - tumo_cloud_net

networks:
  tumo_cloud_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
