version: '3.5'

services:
  tumo-cloud-ui:
    image: registry.cn-hangzhou.aliyuncs.com/tumo/tumo-cloud-ui
    restart: always
    container_name: tumo-cloud-ui
    ports:
      - 8092:80
    networks:
      - tumo_cloud_net

networks:
  tumo_cloud_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/16
